version: "3"

networks:
  imcloudx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.88.10.0/24
          gateway: 172.88.10.1

services:
  ########### dependencies ###########
  etcd: # 配置中心 注册中心
    image: bitnami/etcd:3.5.8
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - "./data/etcd:/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://172.88.10.11:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://172.88.10.11:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      #参数指不用密码可以连接
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
    container_name: etcd
    restart: always
    networks:
      imcloudx:
        ipv4_address: 172.88.10.11 # 172.88.10.11:2379

  etcd-keeper:
    image: lykart/etcdkeeper:v1.1
    container_name: etcd-keeper
    environment:
      - ETCD_BASE=172.88.10.11:2379
      - USERNAME=admin
      - PASSWORD=admin
    depends_on:
      - etcd
    networks:
      imcloudx:
        ipv4_address: 172.88.10.12 # http://172.88.10.12:8080

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      imcloudx:
        ipv4_address: 172.88.10.21 # 172.88.10.21:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    networks:
      imcloudx:
        ipv4_address: 172.88.10.22 # 172.88.10.22:6379
    volumes:
      - ./data/redis:/data
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--requirepass"
      - "123456"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    networks:
      imcloudx:
        ipv4_address: 172.88.10.31 # 172.88.10.31:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "LANG=zh_CN.UTF-8"
      - "TZ=Asia/Shanghai"
    networks:
      imcloudx:
        ipv4_address: 172.88.10.32 # http://172.88.10.32:5601

  jaeger-allinone:
    image: jaegertracing/all-in-one
    container_name: jaeger-allinone
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
      - "ES_TAGS_AS_FIELDS_ALL=true"
    networks:
      imcloudx:
        ipv4_address: 172.88.10.33 # http://172.88.10.33:16686 / http://172.88.10.33:14268
    depends_on:
      - elasticsearch
